- name: Copy Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Copy Prometheus Configuration - Record file
  ansible.builtin.template:
    src: record.yml
    dest: /opt/prometheus/record.yml

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted


