- name: Cleanup old content
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory

#- name: Download backend Code and Extract it
#  ansible.builtin.unarchive:
#    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: "{{ app_loc }}"
#    remote_src: yes

- name: Download backend Code and Extract it
  ansible.builtin.unarchive:
    src: http://admin:Admin123artifactory.rdevopsb73.online:8081/artifactory/{{ component }}/{{ component }}-{{ lookup('aws_ssm', '{{env}}.{{component}}.app_version', region='us-east-1' ) }}.zip
    dest: "{{ app_loc }}"
    remote_src: yes